version: '3.3'

services:
   mongo:
      image: mongo
      container_name: mongodb
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: password
      ports:
         - 27017:27017
      volumes:
         - mongo-data:/home/ubuntu/Imágenes/Pagina_Web/docker/data
volumes:
   mongo-data: